import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/providers/themeProviders'
import Header from '@/components/layout/Header'
import NavAside from '@/components/layout/NavAside'
const font = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '800', '900'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="tr" suppressHydrationWarning>
      <body className={cn(font.className, "bg-white dark:bg-darkerColor text-darkColor dark:text-white overflow-x-hidden")}>
      <ThemeProvider
        attribute='class'
        defaultTheme='system'
        enableSystem={true}
        storageKey='theme'
        >
          <Header/>
          <div className='flex container h-[calc(100vh_-_101px)]'>
          <NavAside/>
          {children}
          </div>
        </ThemeProvider>
        </body>
    </html>
  )
}
